# docker-compose.yml  ← at the root of your repo
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - ./server/.env
    ports:
      - "8000:8000"
    restart: unless-stopped

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    env_file:
      - ./client/.env
    ports:
      - "80:80"
    depends_on:
      - server
    restart: unless-stopped
